name: 9vo.lt
markdown: redcarpet
pygments: true
permalink: /news/:year/:month/:day/:title/
baseurl: "http://9vo.lt"
exclude: [node_modules, mockup, src, CNAME, Gruntfile.js, package.json, params.json, README.md]
